[ALPS08490829] camsys: rename guard() to cam_guard()
rename guard() to cam_guard() since its name is duplicated with a kernel macro

vendor/mediatek/kernel_modules/mtkcam/camsys/isp7sp/cam/mtk_cam-job_state.c:214:44: error: too many arguments provided to function-like macro invocation
                ret = trans->guard ? trans->guard(s_acc, p) : 1;
                                                         ^
/mfs/mtkslt1057/mtk28673/CAS_REAL/1_alps-dev-u0.mp1-kmainline--2023_10_04_02_00/merged/out_krn/target/product/mgk_64_kmainline/obj/KLEAF_OBJ/bazel/output_user_root/output_base/sandbox/processwrapper-sandbox/35/execroot/__main__/kernel-mainline/include/linux/cleanup.h:108:9: note: macro guard defined here
define guard(_name)
        ^

MTK-Commit-Id: 88d8e5432dcca9a3da370749a89509b2326be05c

Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS08490829
Feature: Kernel SI Operation
Change-Id: If473650e6a758da32386b886259ebbc587e3f833