[ALPS08490829] Fix v4l2_async build error
Fix the build error due to Commit adb2dcd5f2d4 ("media: v4l: async: Rename v4l2_async_subdev as v4l2_async_connection") and Commit bda8953e8c3e ("
media: v4l: async: Drop v4l2_async_nf_parse_fwnode_endpoints()")

vendor/mediatek/kernel_modules/mtkcam/camsys/isp7s/cam_legacy/mtk_cam-seninf-drv.c:2424:8: error: call to undeclared function v4l2_async_nf_parse_fwnode_endpoints; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        ret = v4l2_async_nf_parse_fwnode_endpoints
              ^
vendor/mediatek/kernel_modules/mtkcam/camsys/isp7s/cam_legacy/mtk_cam-seninf-drv.c:2425:19: error: invalid application of sizeof to an incomplete type struct v4l2_async_subdev
                (dev, notifier, sizeof(struct v4l2_async_subdev), NULL);
                                ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~

MTK-Commit-Id: 7488c086023958c473bda6f2c19014d06ea824ed

Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS08490829
Feature: Kernel SI Operation
Change-Id: I367f0017b10de9c5900c34a44e06bac872ba50ab