[ALPS08631203] cam: fix kernel-6.12 build error
[Description]
include io.h to fix build error

vendor/mediatek/kernel_modules/mtkcam/camsys/isp8s/cam/mtk_cam-tg-flash.c:84:2: error: call to undeclared function writel_relaxed; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   84 |         writel_relaxed(0x0, raw->base_inner + REG_TG_IR_FLASH_CTL);
      |         ^

[Test]
boot pass

MTK-Commit-Id: aa11ef23f8ac306999ab50c9e05b808792755964

Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS08631203
Feature: Kernel SI Operation
Change-Id: Ib244c9c5195cc45a73012478bb49a4a7a40e1535
(cherry picked from commit 1c6ad76d022294d788d38b9d3e9d7dacce83b6d9)