[ALPS08490829] use container_of() instead of container_of_safe()
Commit 848dba781f19 (container_of: remove container_of_safe())
removes container_of_safe(), so use container_of() instead

vendor/mediatek/kernel_modules/mtkcam/camsys/isp7sp/cam/mtk_cam-seninf-tsrec.c:1168:8: error: call to undeclared function container_of_safe; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        req = container_of_safe(work, struct tsrec_work_request, work);
              ^

MTK-Commit-Id: 4fdc6479aeae7fef83b31b62951a865002a700de

Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS08490829
Feature: Kernel SI Operation
Change-Id: Ib3033dd25d01828e0446923dba7df73a6c6ee523