[ALPS08631203] mtkcam: fix build error due to mainline migration
[Description]
Fix build error according to Commit "4cf6336 Merge tag v6.10-rc1
into android-mainline"
1. include linux/vmalloc
2. fix error due to "use $(src) instead of $(srctree)/$(src) for
source directory"
3. remove second parameter of __assign_str()
4. fix error: no member named num_buffers in struct vb2_queue

[Test]
Build and Boot up

MTK-Commit-Id: ef33348f57eb6aeb051c4cc2cf3890fba4f1998a

Signed-off-by: PoShao Chen <poshao.chen@mediatek.com>
CR-Id: ALPS08631203
Feature: Kernel SI Operation
Change-Id: I7fc2d5427e8fa19d3ef018208c7ad704eca600ba