[ALPS08631203] imgsensor: fix build error
[Description]
Fix build error due to kernel migration.
ERROR: modpost: module imgsensor_isp8s uses symbol dentry_open
from namespace ANDROID_GKI_VFS_EXPORT_ONLY, but does not import it.

[Test]
Boot pass

MTK-Commit-Id: b58c697fa5e2b0a5944ac0f2a12d4caa1f8a4e91

Signed-off-by: poshao.chen <poshao.chen@mediatek.com>
Signed-off-by: swintegrator <swintegrator@mediatek.com>
CR-Id: ALPS08631203
Feature: Kernel SI Operation
Change-Id: Iac4275d2df80c6cd605f2a0f1ff883f85b59731d